### ISSUE TITLE
Cloning a Repo sometimes raises error in `_repos.append(repo)`

### ISSUE THREAD

**Issue by hamishcampbell** [koordinates/kart-qgis-plugin#42] opened 2021-12-01 22:38 UTC
I'm still tracking down the exact replication steps, but I'm regularly getting this error when cloning repositories:

```
Traceback (most recent call last):
  File "/Users/hamish/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 144, in wrapper
    f(*args)
  File "/Users/hamish/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/kartapi.py", line 50, in inner
    return f(*args)
  File "/Users/hamish/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/dockwidget.py", line 254, in cloneRepo
    addRepo(repo)
  File "/Users/hamish/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/kartapi.py", line 244, in addRepo
    _repos.append(repo)
AttributeError: 'NoneType' object has no attribute 'append'
```

The repo is still cloned and added to the panel correctly.

Using latest kart-qgis-plugin c65e57a6f9d376812e0314427584d92798295117
QGIS 3.20 / MacOS

**Comment by volaya** [comment] 2021-12-02 09:01
It should be fixed now

**Comment by rcoup** [comment] 2021-12-14 12:56
I can't reproduce it, so lets mark it as fixed unless someone else encounters it.

**Closed by rcoup** 2021-12-14 12:56 UTC
